name: Publish Docker

on: 
  push: 
    branches: [develop]

jobs: 
  build: 
    run-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@develop
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@develop
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/IvanPeleshok/nestjs-sample/api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"